<?php
return array (
  1 => 
  array (
    'catid' => '1',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '1,2,3,4,5',
    'catname' => '网站介绍',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'about',
    'url' => 'http://www.cms.com/html/about/',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)',
    'listorder' => '1',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'wangzhanjieshao',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '1',
    'content_ishtml' => NULL,
    'category_ruleid' => '1',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  2 => 
  array (
    'catid' => '2',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '1',
    'arrparentid' => '0,1',
    'child' => '0',
    'arrchildid' => '2',
    'catname' => '关于我们',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'about/',
    'catdir' => 'aboutus',
    'url' => 'http://www.cms.com/index.php?m=content&c=index&a=lists&catid=2',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"pxgridshtml5","page_template":"page_about","meta_title":"\\u5173\\u4e8e\\u6211\\u4eec","meta_keywords":"\\u5173\\u4e8e\\u6211\\u4eec","meta_description":"\\u5173\\u4e8e\\u6211\\u4eec","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '1',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'guanyuwomen',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  3 => 
  array (
    'catid' => '3',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '1',
    'arrparentid' => '0,1',
    'child' => '0',
    'arrchildid' => '3',
    'catname' => '联系方式',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'about/',
    'catdir' => 'contactus',
    'url' => 'http://www.cms.com/index.php?m=content&c=index&a=lists&catid=3',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"pxgridshtml5","page_template":"page_about","meta_title":"\\u8054\\u7cfb\\u65b9\\u5f0f","meta_keywords":"\\u8054\\u7cfb\\u65b9\\u5f0f","meta_description":"\\u8054\\u7cfb\\u65b9\\u5f0f","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '2',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'lianxifangshi',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  4 => 
  array (
    'catid' => '4',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '1',
    'arrparentid' => '0,1',
    'child' => '0',
    'arrchildid' => '4',
    'catname' => '版权声明',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'about/',
    'catdir' => 'copyright',
    'url' => 'http://www.cms.com/index.php?m=content&c=index&a=lists&catid=4',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'版权声明\',
  \'meta_keywords\' => \'版权声明\',
  \'meta_description\' => \'版权声明\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)',
    'listorder' => '3',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'banquanshengming',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  5 => 
  array (
    'catid' => '5',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '1',
    'arrparentid' => '0,1',
    'child' => '0',
    'arrchildid' => '5',
    'catname' => '招聘信息',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'about/',
    'catdir' => 'hr',
    'url' => 'http://www.cms.com/html/about/hr/',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)',
    'listorder' => '4',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zhaopinxinxi',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '1',
    'content_ishtml' => NULL,
    'category_ruleid' => '1',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => 'banner',
    'style' => '',
    'image' => 'http://www.cms.com/uploadfile/2017/0418/20170418011524795.jpg',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'banner',
    'url' => 'http://www.cms.com/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"pxgridshtml5","category_template":"category_ad","list_template":"list_ad","show_template":"show_ad","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'banner',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>